sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
before_install: gem install bundler
gemfile:
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-edge
